[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-js-swc"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "1", features = ["serde-json"] }
napi-derive = "1"
swc_ecmascript = { version = "0.36.0", features = ["parser", "transforms", "module", "optimization", "react", "typescript", "utils", "visit", "codegen", "utils"] }
swc_ecma_preset_env = "0.20.1"
swc_common = { version = "0.10.19", features = ["tty-emitter", "sourcemap"] }
swc_atoms = "0.2.6"
indoc = "1.0.3"
serde = "1.0.123"
Inflector = "0.11.4"
data-encoding = "2.3.2"
sha-1 = "0.9.4"
dunce = "1.0.1"

[target.'cfg(target_os = "macos")'.dependencies]
jemallocator = { version = "0.3.2", features = ["disable_initial_exec_tls"] }

[target.'cfg(windows)'.dependencies]
mimalloc = { version = "0.1.25", default-features = false }

[build-dependencies]
napi-build = { version = "1" }
